app_name = "dash"
app_mode = "DEV" # DEBUG, DEV, PROD

app_port = 7100
grpc_port = 7101

db_host = "localhost:8000"
db_user="user"
db_password = "password"
db_name = "dashboard-db"
db_namespace = "dashboard-ns"
# DEFINE LOGIN johndoe ON DATABASE PASSWORD 'password123'