name = "dash"
port = 8080
mode = "DEBUG" # DEV, PROD

# DEFINE LOGIN johndoe ON DATABASE PASSWORD 'password123'

db_host = "localhost:8000"
db_user="dashuser"
db_password = "password123"
db_name = "dashboard"
db_namespace = "dashboard"