import { RootLayout } from '../components/root-layout/root-layout';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  'use client';
  return (
    <html lang="en" className="dark">
      <body>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
