name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt install -y protobuf-compiler libprotobuf-dev
      - uses: actions/checkout@v3
      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          default: true
          toolchain: 1.71.0
      - name: build
        run: cargo build --verbose
      - name: run tests
        run: cargo test --verbose
