name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install rust toolchain with clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          default: true
          toolchain: 1.67.1
          components: clippy
      - name: Run clippy linter
        run: cargo clippy
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
